Refactor whatif promise
reneolivo/whatif pull request #1
Opened 2016-10-02 22:07 UTC by reneolivo

The WhatIfPromise has been revamped from the ground up.

2016-10-03 00:50 UTC, rmariuzzo requested changes
@reneolivo I added a few comment that I consider should be addressed.

2016-10-03 00:50 UTC, rmariuzzo commented on README.md
>  whatif(theThemeColor === 'red')
Should be `whatIf`.

2016-10-03 00:50 UTC, rmariuzzo commented on spec/whatif.spec.js
> +    const wrapper = { WhatIfPromise: WhatIfPromise };
You could use **object literal property value shorthand** as: `{ WhatIfPromise }`

2016-10-03 02:44 UTC, reneolivo commented on spec/whatif.spec.js
> +    const wrapper = { WhatIfPromise: WhatIfPromise };
I completely forgot about that... thanks!!!

2016-10-03 03:22 UTC, rmariuzzo commented on spec/whatif.spec.js
> +    const wrapper = { WhatIfPromise: WhatIfPromise };
You are welcome sir 🙇

2016-10-08 20:17 UTC, reneolivo commented
Thanks for the tips! I'll be merging this one now.

2016-10-08 20:17 UTC, merged